<?php
$dictionary["bd01_ERP_Quote"]["fields"]["bd01_erp_quote_quotes"] = array (
  'name' => 'bd01_erp_quote_quotes',
  'type' => 'link',
  'relationship' => 'bd01_erp_quote_quotes',
  'source' => 'non-db',
  'module' => 'Quotes',
  'bean_name' => 'Quote',
  'side' => 'right',
  'vname' => 'LBL_BD01_ERP_QUOTE_QUOTES_FROM_BD01_ERP_QUOTE_TITLE',
  'id_name' => 'bd01_erp_quote_quotesquotes_ida',
  'link-type' => 'one',
);
$dictionary["bd01_ERP_Quote"]["fields"]["bd01_erp_quote_quotes_name"] = array (
  'name' => 'bd01_erp_quote_quotes_name',
  'type' => 'relate',
  'source' => 'non-db',
  'vname' => 'LBL_BD01_ERP_QUOTE_QUOTES_FROM_QUOTES_TITLE',
  'save' => true,
  'id_name' => 'bd01_erp_quote_quotesquotes_ida',
  'link' => 'bd01_erp_quote_quotes',
  'table' => 'quotes',
  'module' => 'Quotes',
  'rname' => 'name',
);
$dictionary["bd01_ERP_Quote"]["fields"]["bd01_erp_quote_quotesquotes_ida"] = array (
  'name' => 'bd01_erp_quote_quotesquotes_ida',
  'type' => 'id',
  'source' => 'non-db',
  'vname' => 'LBL_BD01_ERP_QUOTE_QUOTES_FROM_BD01_ERP_QUOTE_TITLE_ID',
  'id_name' => 'bd01_erp_quote_quotesquotes_ida',
  'link' => 'bd01_erp_quote_quotes',
  'table' => 'quotes',
  'module' => 'Quotes',
  'rname' => 'id',
  'reportable' => false,
  'side' => 'right',
  'massupdate' => false,
  'duplicate_merge' => 'disabled',
  'hideacl' => true,
);
