<?php

// What earlier Bench Dogs versions installed and the current one no longer ships; pack.php puts an empty placeholder under leftovers/ for each file. (🔒2126b)
return array(
    // Deleted wherever present.
    'remove' => array(
        // Extension fragments of retired features (K-1, K-4 registrations, D-3) (🔒 1508, 🔒 1514).
        'custom/Extension/modules/Contacts/Ext/Vardefs/bd_contact_sync_fields.php',
        'custom/Extension/modules/ERP_OrderLines/Ext/Vardefs/bd_shipped_value.php',
        'custom/Extension/modules/ERP_Orders/Ext/Vardefs/bd_shipped_value_total.php',
        'custom/Extension/modules/Opportunities/Ext/Vardefs/bd_forecast_provenance.php',
        'custom/Extension/modules/Opportunities/Ext/Vardefs/bd_governing_origin.php',
        'custom/Extension/modules/Products/Ext/Vardefs/bd_cost_worksheet.php',
        'custom/Extension/modules/Products/Ext/Vardefs/bd_deleted_erp_sync_key.php',
        'custom/Extension/modules/Products/Ext/Vardefs/bd_governing_line_fields.php',
        'custom/Extension/modules/Products/Ext/Vardefs/bd_line_order_fields.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd01_erp_quote_quotes.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_comment_pending.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_comment_requested_at.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_comment_text.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_deleted_erp_sync_key.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_erp_kpi_inputs.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_erp_stage.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_erp_stage_code.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_erp_total.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_estimating_turnaround.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_governing_line.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_order_requested_at.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_priced_at.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_print_link.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_print_requested_at.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_print_status.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_quantity_breaks.php',
        'custom/Extension/modules/Quotes/Ext/Vardefs/bd_reason_code.php',
        'custom/Extension/modules/RevenueLineItems/Ext/Vardefs/bd_deliverable_key.php',
        'custom/Extension/modules/bd01_ERP_Quote/Ext/Vardefs/bd01_erp_quote_lines.php',
        'custom/Extension/modules/bd01_ERP_Quote/Ext/Vardefs/bd01_erp_quote_quotes.php',
        'custom/Extension/modules/bd01_ERP_Quote/Ext/Vardefs/bd_estimating_turnaround.php',
        'custom/Extension/modules/bd01_ERP_Quote/Ext/Vardefs/bd_materialize.php',
        'custom/Extension/modules/bd01_ERP_Quote/Ext/Vardefs/bd_quote_completion.php',
        'custom/Extension/modules/bd01_ERP_Quote/Ext/Vardefs/bd_reason_code_erp.php',
        'custom/Extension/modules/bd01_ERP_Quote_Cost/Ext/Vardefs/bd01_erp_line_costs.php',
        'custom/Extension/modules/bd01_ERP_Quote_Line/Ext/Vardefs/bd01_erp_line_costs.php',
        'custom/Extension/modules/bd01_ERP_Quote_Line/Ext/Vardefs/bd01_erp_quote_lines.php',
        'custom/Extension/modules/bd01_ERP_Quote_Line/Ext/Vardefs/bd_governing_origin.php',
        'custom/Extension/modules/Accounts/Ext/Language/en_us.bd_action_buttons.php',
        'custom/Extension/modules/ERP_OrderLines/Ext/Language/en_us.bd_shipped_value.php',
        'custom/Extension/modules/ERP_Orders/Ext/Language/en_us.bd_shipped_value_total.php',
        'custom/Extension/modules/Opportunities/Ext/Language/en_us.bd_governing_origin.php',
        'custom/Extension/modules/Products/Ext/Language/en_us.bd_cost_worksheet.php',
        'custom/Extension/modules/Products/Ext/Language/en_us.bd_deleted_erp_sync_key.php',
        'custom/Extension/modules/Products/Ext/Language/en_us.bd_governing_line_fields.php',
        'custom/Extension/modules/Products/Ext/Language/en_us.bd_line_order.php',
        'custom/Extension/modules/Quotes/Ext/Language/en_us.bd_action_buttons.php',
        'custom/Extension/modules/Quotes/Ext/Language/en_us.bd_deleted_erp_sync_key.php',
        'custom/Extension/modules/Quotes/Ext/Language/en_us.bd_erp_fields.php',
        'custom/Extension/modules/Quotes/Ext/Language/en_us.bd_quantity_breaks.php',
        'custom/Extension/application/Ext/Language/_override_en_us.bd_country_lookup.php',
        'custom/Extension/application/Ext/Language/en_us.bd_country_lookup.php',
        'custom/Extension/application/Ext/Language/en_us.bd_erp_stage_list.php',
        'custom/Extension/application/Ext/Language/en_us.bd_stage_doms.php',
        'custom/Extension/modules/bd01_ERP_Quote/Ext/Language/en_us.bd01_erp_quote_quotes_subpanel.php',
        'custom/Extension/modules/bd01_ERP_Quote/Ext/Language/en_us.bd_turnaround_fields.php',
        'custom/Extension/modules/bd01_ERP_Quote_Cost/Ext/Language/en_us.bd01_erp_line_costs_subpanel.php',
        'custom/Extension/modules/bd01_ERP_Quote_Line/Ext/Language/en_us.bd01_erp_quote_lines_subpanel.php',
        'custom/Extension/modules/bd01_ERP_Quote_Line/Ext/Language/en_us.bd_governing_origin.php',
        'custom/Extension/modules/Accounts/Ext/LogicHooks/bd_account_country_guard.php',
        'custom/Extension/modules/Contacts/Ext/LogicHooks/bd_contact_sync.php',
        'custom/Extension/modules/Products/Ext/LogicHooks/bd_governing_autoselect.php',
        'custom/Extension/modules/Products/Ext/LogicHooks/bd_governing_line.php',
        'custom/Extension/modules/Quotes/Ext/LogicHooks/bd_estimating_notification.php',
        'custom/Extension/modules/Quotes/Ext/LogicHooks/bd_estimating_turnaround.php',
        'custom/Extension/modules/Quotes/Ext/LogicHooks/bd_kinetic_opportunity.php',
        'custom/Extension/modules/Quotes/Ext/LogicHooks/bd_primary_quote.php',
        'custom/Extension/modules/Quotes/Ext/LogicHooks/bd_quote_carrier_canonical.php',
        'custom/Extension/modules/Quotes/Ext/LogicHooks/bd_quote_kpi.php',
        'custom/Extension/modules/Quotes/Ext/LogicHooks/bd_sync_key_release.php',
        'custom/Extension/modules/bd01_ERP_Quote/Ext/LogicHooks/bd_quote_reflection.php',
        'custom/Extension/modules/bd01_ERP_Quote_Line/Ext/LogicHooks/bd_governing_autoselect.php',
        'custom/Extension/modules/bd01_ERP_Quote_Line/Ext/LogicHooks/bd_governing_line.php',
        'custom/Extension/modules/bd01_ERP_Quote_Line/Ext/LogicHooks/bd_quote_line_refresh.php',
        'custom/Extension/modules/bd01_ERP_Quote_Line/Ext/LogicHooks/bd_rli_refresh.php',
        'custom/Extension/application/Ext/TableDictionary/zzz_bd_quotes_erp_orders_history.php',
        'custom/Extension/modules/Accounts/Ext/clients/base/layouts/subpanels/bd_subpanel_erp_quotes.php',
        'custom/Extension/modules/Products/Ext/clients/base/layouts/subpanels/bd_subpanel_rung_costs.php',
        'custom/Extension/modules/Quotes/Ext/clients/base/layouts/subpanels/_overridesubpanel-for-quotes-bd01_erp_quote_quotes.php',
        'custom/Extension/modules/Quotes/Ext/clients/base/layouts/subpanels/bd_subpanel_erp_quotes.php',
        'custom/Extension/modules/bd01_ERP_Quote/Ext/clients/base/layouts/subpanels/_overridesubpanel-for-bd01_erp_quote-bd01_erp_quote_lines.php',
        'custom/Extension/modules/bd01_ERP_Quote/Ext/clients/base/layouts/subpanels/bd_subpanel_quote_lines.php',
        'custom/Extension/modules/bd01_ERP_Quote_Line/Ext/clients/base/layouts/subpanels/_overridesubpanel-for-bd01_erp_quote_line-bd01_erp_line_costs.php',
        'custom/Extension/modules/bd01_ERP_Quote_Line/Ext/clients/base/layouts/subpanels/bd_subpanel_line_costs.php',
        'custom/Extension/modules/ERP_OrderLines/Ext/clients/base/views/record/bd_shipped_value.php',
        'custom/Extension/modules/ERP_Orders/Ext/clients/base/views/record/bd_shipped_value_total.php',
        // K-5: the accumulated stage vocabulary fragment (🔒 314).
        'custom/Extension/application/Ext/Language/en_us.zz_bd_stage_doms.php',
        // Class files of retired features: K-4's tombstone and the others (G280, 🔒 1567, 🔒 1508, 🔒 1511).
        'custom/dropdowntemplates/bd_stage_doms.append.php',
        'custom/modules/Accounts/BdAccountCountryGuard.php',
        'custom/modules/Contacts/BdContactSyncHook.php',
        'custom/modules/Opportunities/BdAutoSelectedReport.php',
        'custom/modules/Products/BdGoverningAutoSelect.php',
        'custom/modules/Products/BdGoverningAutoSelectHook.php',
        'custom/modules/Products/BdGoverningLineHook.php',
        'custom/modules/Products/BdGoverningLineLock.php',
        'custom/modules/Products/BdGoverningValuationRefresh.php',
        'custom/modules/Products/BdSyncKeyReleaseHook.php',
        'custom/modules/Quotes/BdEstimatingNotificationHook.php',
        'custom/modules/Quotes/BdEstimatingTurnaround.php',
        'custom/modules/Quotes/BdKineticOpportunityHook.php',
        'custom/modules/Quotes/BdPrimaryQuoteHook.php',
        'custom/modules/Quotes/BdQliColumnTemplate.php',
        'custom/modules/Quotes/BdQliColumnsLayout.php',
        'custom/modules/Quotes/BdQuantityBreakTab.php',
        'custom/modules/Quotes/BdQuantityBreaksTabLayout.php',
        'custom/modules/Quotes/BdQuoteCarrierCanonicalHook.php',
        'custom/modules/Quotes/BdQuoteKpiHook.php',
        'custom/modules/Quotes/BdSubmitOrderPlan.php',
        // Moved or retired by 0.9.42-rc86 / rc87: the old BdAdmRules path, the option functions (now BdAdmRules methods) and the empty REST stub.
        'custom/modules/Quotes/BdAdmRules.php',
        'custom/modules/Quotes/BdAdmLookupOptions.php',
        'custom/clients/base/api/BdBenchDogsActionsApi.php',
    ),
    // Deleted only when the file holds a body Bench Dogs shipped (md5): another writer shares these paths. (G599, G594)
    'remove_if_bench' => array(
        // Sugar's own dropdown-style sync writes this path too.
        'custom/Extension/application/Ext/DropdownsStyle/sales_stage_dom_style.php' => array(
            '4f3312f2ea33e251f7e568f624bc4eb9',
            '4be4aa516991c01d838f4c98ba333fd9',
            '1c851a6bed5179086ee7cabe3bce6613',
            'b3a90dcc1702b3191bef89b63a245ee0',
        ),
        // Partial Fulfillment's release-stage provider path.
        'custom/modules/Quotes/ErpQuoteHooks/OpportunityReleaseStagePolicy.php' => array(
            'faf17dd27859c430cbd26fa4b07b6029',
            '8333e547ebad159117fae54c50d2d4c0',
            '43eecd851e272aa42aed84ded3b83e0d',
            'cf0969c0c3f76dc50307aed4c4e903f0',
            'b442f750afbf9e96a1f434809ac5bd0a',
            'da037878d13206aee9124a397de986a4',
            'e5e6e3fff432a5dcd6624accf6bb8598',
            '32fd2941e268cc8c9153e0f865c0ffc7',
        ),
        // The order adapter, whose planner (above) no longer answers.
        'custom/modules/Quotes/ErpQuoteHooks/ResolveOrderableLines.php' => array(
            'f6c3d4747ccbf822e0c6ba27b6360656',
        ),
    ),
    // Whole directories nothing else writes (the retired bd01 modules and button fields), removed with ModuleInstaller::uninstall_customizations().
    'directories' => array(
        'bd01_ERP_Quote',
        'bd01_ERP_Quote_Line',
        'bd01_ERP_Quote_Cost',
        'Accounts/clients/base/fields/bd-create-opp-quote',
        'Quotes/clients/base/fields/bd-best-pricing',
        'Quotes/clients/base/fields/bd-order-selected',
        'Quotes/clients/base/fields/bd-order-winning',
        'Quotes/clients/base/fields/bd-send-estimating',
    ),
);
