#!/usr/bin/env python3
"""Re-sync MLP002's deny-lists in mlp_lint.py with the Sugar source of truth.

The cloud scanner's lists live in ModuleInstall/ModuleScanner.php as private
arrays. Keeping our copy by hand cost this repository two refused releases:

  * ERP-Epicor 1.1.24-rc29, 2026-09-15: `Code attempted to call denylisted
    function "array_filter" on line 453`, after our linter - carrying a
    33-name list written from memory - reported it clean.
  * ERP-Epicor 1.1.100, 2026-09-21 (G222): `... "stream_resolve_include_path"
    on line 2870`, after the linter - carrying $blackList, regenerated by an
    earlier version of THIS script - reported it clean. That version read
    `$blackList` only and never noticed `$unsafeHttpClientFunctions`, which the
    scanner merges into it when EnhancedModuleChecks is on (always, on
    SugarCloud).

So this reads EVERY list the scanner's BlacklistVisitor is handed, and the
feature-flag merges that widen them, and `--check` fails when any of them, or
any line range mlp_lint.SCANNER_SOURCE records for them, has moved.

Usage:
  python3 scripts/regen_denylist.py /path/to/SugarEnt-Full-26.1.0           # print literals
  python3 scripts/regen_denylist.py /path/to/SugarEnt-Full-26.1.0 --check   # exit 1 on drift

The arrays read, and where they were on 26.1.0 and 25.2.0 (identical files):
  $validExt :74 · $classBlackList :75-105 · $blackList :106-427 ·
  $unsafeHttpClientFunctions :428-532 · $methodsBlackList :534-542 ·
  EnhancedModuleChecks merge :610-611 · SecureSmarty class merge :614-616
"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

ARRAYS = ("validExt", "classBlackList", "blackList", "unsafeHttpClientFunctions", "methodsBlackList")
EXEMPT_ARRAYS = ("blackListExempt", "classBlackListExempt")
NAME_RE = re.compile(r"[a-z_][a-z0-9_\\]*")


def _array_span(lines: list[str], name: str) -> tuple[int, int]:
    """1-based (first, last) line of `private $name = [ ... ];`."""
    start = next(
        (i for i, l in enumerate(lines) if re.match(r"\s*private \$" + re.escape(name) + r"\s*=\s*\[", l)),
        None,
    )
    if start is None:
        raise SystemExit(f"ModuleScanner.php no longer declares private ${name} = [ ... ]")
    depth = 0
    for i in range(start, len(lines)):
        # One line inside $blackList is a grep recipe in a comment and yields
        # `s/\-/\_/g` if comments are not stripped first.
        code = re.sub(r"//.*", "", lines[i])
        depth += code.count("[") - code.count("]")
        if depth <= 0:
            return start + 1, i + 1
    raise SystemExit(f"unterminated ${name} in ModuleScanner.php")


def extract(scanner_php: Path) -> dict:
    """Every list BlacklistVisitor and isValidExtension are handed, plus where."""
    text = scanner_php.read_text()
    lines = text.splitlines()
    out: dict = {"spans": {}, "sha1": hashlib.sha1(text.encode()).hexdigest()}
    for name in ARRAYS + EXEMPT_ARRAYS:
        first, last = _array_span(lines, name)
        out["spans"][name] = (first, last)
        body = [re.sub(r"//.*", "", l) for l in lines[first - 1:last]]
        # Strip the `private $x = [` prefix so its own brackets are not read.
        body[0] = body[0].split("=", 1)[1]
        if name == "methodsBlackList":
            plain, keyed = set(), {}
            for l in body:
                m = re.match(r"\s*'([^']+)'\s*=>\s*\[(.*)\]", l)
                if m:
                    keyed[m.group(1).lower()] = {v.lower() for v in re.findall(r"'([^']+)'", m.group(2))}
                else:
                    plain |= {v.lower() for v in re.findall(r"'([^']+)'", l)}
            out["methodsBlackList"] = plain
            out["methodsBlackListKeyed"] = keyed
            continue
        names = [n.lower() for l in body for n in re.findall(r"'([^']+)'", l)]
        out[name] = {n for n in names if NAME_RE.fullmatch(n)}
        out[name + "_count"] = len(names)

    merge = next(
        (i + 1 for i, l in enumerate(lines)
         if "array_merge($this->blackList, $this->unsafeHttpClientFunctions)" in l),
        None,
    )
    if merge is None:
        raise SystemExit(
            "the EnhancedModuleChecks merge of $unsafeHttpClientFunctions into "
            "$blackList has moved or gone; re-read ModuleScanner::__construct"
        )
    guard = lines[merge - 2] if merge >= 2 else ""
    if "EnhancedModuleChecks" not in guard:
        raise SystemExit(f"line {merge - 1} no longer guards the merge on EnhancedModuleChecks")
    out["spans"]["enhancedModuleChecksMerge"] = (merge - 1, merge)

    smarty = next(
        (i + 1 for i, l in enumerate(lines) if "SecureSmarty::getName()" in l),
        None,
    )
    if smarty is None:
        raise SystemExit("the SecureSmarty class merge has moved or gone")
    merged = re.findall(r"'([^']+)'", lines[smarty])
    out["secureSmarty"] = {m.lower() for m in merged}
    out["spans"]["secureSmartyMerge"] = (smarty, smarty + 2)
    return out


def _literal(names, per=4) -> str:
    names = sorted(names)
    return "\n".join(
        "    " + " ".join(f'"{n}",' for n in names[i:i + per])
        for i in range(0, len(names), per)
    ).replace("\\", "\\\\")


def check(root: Path) -> list[str]:
    """Differences between mlp_lint.py and the scanner at `root`. Empty = in sync."""
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import mlp_lint

    php = root / "ModuleInstall" / "ModuleScanner.php"
    got = extract(php)
    problems: list[str] = []

    def compare(label, ours, theirs):
        ours, theirs = set(ours), set(theirs)
        if ours != theirs:
            problems.append(
                f"{label}: missing from mlp_lint {sorted(theirs - ours)}, "
                f"not in the scanner {sorted(ours - theirs)}"
            )

    compare("$blackList", mlp_lint.SCANNER_BLACKLIST, got["blackList"])
    compare("$unsafeHttpClientFunctions", mlp_lint.SCANNER_UNSAFE_HTTP_CLIENT_FUNCTIONS,
            got["unsafeHttpClientFunctions"])
    compare("$classBlackList", mlp_lint.SCANNER_CLASS_BLACKLIST, got["classBlackList"])
    compare("SecureSmarty classes", mlp_lint.SCANNER_SECURE_SMARTY_CLASSES, got["secureSmarty"])
    compare("$methodsBlackList (plain)", mlp_lint.SCANNER_METHOD_BLACKLIST, got["methodsBlackList"])
    ours_keyed = {k: set(v) for k, v in mlp_lint.SCANNER_CLASS_METHOD_BLACKLIST.items()}
    if ours_keyed != got["methodsBlackListKeyed"]:
        problems.append(
            f"$methodsBlackList (class-scoped): mlp_lint {ours_keyed} vs scanner "
            f"{got['methodsBlackListKeyed']}"
        )
    compare("$validExt", mlp_lint.SCANNER_VALID_EXTENSIONS, got["validExt"])
    for name in EXEMPT_ARRAYS:
        if got[name]:
            problems.append(
                f"${name} is no longer empty in the source: {sorted(got[name])}; "
                f"the exempt names must come OFF the lists above"
            )
    for key, span in got["spans"].items():
        if key in EXEMPT_ARRAYS:
            continue
        recorded = mlp_lint.SCANNER_SOURCE.get(key)
        if recorded is not None and tuple(recorded) != tuple(span):
            problems.append(
                f"SCANNER_SOURCE[{key!r}] says ModuleScanner.php:{recorded[0]}-{recorded[1]}, "
                f"the source has it at :{span[0]}-{span[1]}"
            )
    if mlp_lint.SCANNER_SOURCE.get("sha1") != got["sha1"]:
        problems.append(
            f"ModuleScanner.php sha1 is {got['sha1']}, SCANNER_SOURCE records "
            f"{mlp_lint.SCANNER_SOURCE.get('sha1')}: the file changed, re-read it "
            f"for anything new even if every list above still matches"
        )
    return problems


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__)
        return 2
    root = Path(argv[0])
    php = root / "ModuleInstall" / "ModuleScanner.php"
    if not php.exists():
        print(f"not found: {php}", file=sys.stderr)
        return 2
    if "--check" in argv[1:]:
        problems = check(root)
        if problems:
            print(f"mlp_lint.py has drifted from {php}:")
            for p in problems:
                print("  - " + p)
            return 1
        print(f"mlp_lint.py matches {php} (sha1 {extract(php)['sha1']})")
        return 0
    got = extract(php)
    print(f"# From {php} (sha1 {got['sha1']})")
    for key, (a, b) in got["spans"].items():
        print(f"#   {key}: :{a}-{b}")
    for name, label in (
        ("blackList", "SCANNER_BLACKLIST"),
        ("unsafeHttpClientFunctions", "SCANNER_UNSAFE_HTTP_CLIENT_FUNCTIONS"),
        ("classBlackList", "SCANNER_CLASS_BLACKLIST"),
        ("secureSmarty", "SCANNER_SECURE_SMARTY_CLASSES"),
        ("methodsBlackList", "SCANNER_METHOD_BLACKLIST"),
        ("validExt", "SCANNER_VALID_EXTENSIONS"),
    ):
        print(f"\n# {len(got[name])} names\n{label} = frozenset({{\n{_literal(got[name])}\n}})")
    print(f"\nSCANNER_CLASS_METHOD_BLACKLIST = {got['methodsBlackListKeyed']!r}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
