<?php
$dictionary["bd01_ERP_Quote_Line"]["fields"]["bd01_erp_quote_lines"] = array (
  'name' => 'bd01_erp_quote_lines',
  'type' => 'link',
  'relationship' => 'bd01_erp_quote_lines',
  'source' => 'non-db',
  'module' => 'bd01_ERP_Quote',
  'bean_name' => 'bd01_ERP_Quote',
  'side' => 'right',
  'vname' => 'LBL_BD01_ERP_QUOTE_LINES_FROM_BD01_ERP_QUOTE_LINE_TITLE',
  'id_name' => 'bd01_erp_quote_linesbd01_erp_quote_ida',
  'link-type' => 'one',
);
$dictionary["bd01_ERP_Quote_Line"]["fields"]["bd01_erp_quote_lines_name"] = array (
  'name' => 'bd01_erp_quote_lines_name',
  'type' => 'relate',
  'source' => 'non-db',
  'vname' => 'LBL_BD01_ERP_QUOTE_LINES_FROM_BD01_ERP_QUOTE_TITLE',
  'save' => true,
  'id_name' => 'bd01_erp_quote_linesbd01_erp_quote_ida',
  'link' => 'bd01_erp_quote_lines',
  'table' => 'bd01_erp_quote',
  'module' => 'bd01_ERP_Quote',
  'rname' => 'name',
);
$dictionary["bd01_ERP_Quote_Line"]["fields"]["bd01_erp_quote_linesbd01_erp_quote_ida"] = array (
  'name' => 'bd01_erp_quote_linesbd01_erp_quote_ida',
  'type' => 'id',
  'source' => 'non-db',
  'vname' => 'LBL_BD01_ERP_QUOTE_LINES_FROM_BD01_ERP_QUOTE_LINE_TITLE_ID',
  'id_name' => 'bd01_erp_quote_linesbd01_erp_quote_ida',
  'link' => 'bd01_erp_quote_lines',
  'table' => 'bd01_erp_quote',
  'module' => 'bd01_ERP_Quote',
  'rname' => 'id',
  'reportable' => false,
  'side' => 'right',
  'massupdate' => false,
  'duplicate_merge' => 'disabled',
  'hideacl' => true,
);
